#!/bin/sh

USAGE="Usage:  play LINK\n"

if [[ $# -ne 1 ]]; then
  echo "\"play\" requires 1 argument.\n"
  echo $USAGE
  exit 1
fi

if ! [[ $1 =~ ^acestream:\/\/([a-zA-Z0-9]+)$ ]]; then
  echo "\"play\" requires valid acestream link.\n"
  echo $USAGE
  exit 1
fi

SOURCE_LINK="acestream://"
FINAL_LINK="http://127.0.0.1:6878/ace/getstream?id="

pkill -f "VLC"
/Applications/VLC.app/Contents/MacOS/VLC --play-and-exit ${1/$SOURCE_LINK/$FINAL_LINK} &> /dev/null &
