#!/bin/sh

BASEDIR=$(dirname "$0")

if [[ "$(docker images -q imaxmelnyk-acestream)" == "" ]]; then
  docker build "$BASEDIR" -t imaxmelnyk-acestream
fi

if [[ "$(docker ps -aqf name=imaxmelnyk-acestream)" == "" ]]; then
  docker create -p 6878:6878 --name imaxmelnyk-acestream imaxmelnyk-acestream
fi

docker start imaxmelnyk-acestream
